### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by andewq** [RuslanUC/RemoteAuthClient#15]
Captcha!
Task exception was never retrieved
future: <Task finished name='Task-177' coro=<RemoteAuthClient.run() done, defined at C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\remoteauthclient\remoteauthclient.py:196> exception=WebDriverException("'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home")>
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\remoteauthclient\remoteauthclient.py", line 199, in run
    await self._task
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\remoteauthclient\remoteauthclient.py", line 181, in _run
    encryptedToken = await self._getToken(p["ticket"])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\remoteauthclient\remoteauthclient.py", line 138, in _getToken
    captcha_key = await self._event("captcha", captcha_data=j)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\remoteauthclient\remoteauthclient.py", line 105, in _event
    return await handler(**kwargs)
  File "C:\Users\Hp\Desktop\bot\bot-main\main.py", line 141, in on_captcha
    captcha_key = await solver.solve(custom_params={"rqdata": captcha_data["captcha_rqdata"]})
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 375, in solve
    "n": await self._getN(),
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 130, in _getN
    return await self._solve_hsw(d['l'])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 153, in _solve_hsw
    return await get_event_loop().run_in_executor(ThreadPoolExecutor(4), _hsw)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\async_hcaptcha\asynchcaptcha.py", line 148, in _hsw
    driver = Chrome(service=Service(**self.chromedriver_args), options=options)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by andewq** [comment]
I solved this problem
You need to add the driver folder with the chromedriver file
