### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by TheBogler** [RuslanUC/RemoteAuthClient#19]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\wes23\Desktop\main.py", line 321, in <module>
    Init()
  File "C:\Users\wes23\Desktop\main.py", line 104, in Init
    bot.run(botToken)
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\site-packages\nextcord\client.py", line 853, in run
    loop.run_forever()
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\wes23\AppData\Local\Programs\Python\Python310\lib\site-packages\remoteauthclient\remoteauthclient.py", line 232, in _run
    log.error("RemoteAuthClient disconnected with error.", err)
Message: 'RemoteAuthClient disconnected with error.'
Arguments: (ConnectionClosedError(Close(code=4001, reason='Decode Error'), Close(code=4001, reason='Decode Error'), True),)

**Comment by TheBogler** [comment]
((

**Comment by RuslanUC** [comment]
Try updading to latest version (or installing from github), I can't reproduce this error.

**Comment by TheBogler** [comment]
Не работает(
