### ISSUE TITLE
How could I fix this issue?

### ISSUE THREAD

**Issue by tiktokfollowed** [RuslanUC/RemoteAuthClient#7]
Hi!

I used to use this script a week ago and it would work perfectly fine, now I am getting this error, not really sure what to do ;/

What should I fix? Where is the problem?
Im really a begginer.
https://hastebin.com/pofokuyoxu.py <- code is here, since it wouldnt let me paste

The error says:

Task exception was never retrieved
future: <Task finished name='Task-22' coro=<start.<locals>.verification_callback.<locals>.RemoteAuthClient.run() done, defined at <...\main.py:171> exception=AttributeError("'NoneType' object has no attribute 'cancel'")>
Traceback (most recent call last):
  File "...\main.py", line 216, in run
    self._heartbeatTask.cancel()
**AttributeError: 'NoneType' object has no attribute 'cancel'**

What should I fix? Where is the problem? Anything helps <3

**Comment by RuslanUC** [comment]
Update remoteauthclient to latest version (1.4.0b3). Also, it can be a captcha response, in this way you should use proxies or solve captcha (examples in readme.md).

**Comment by tiktokfollowed** [comment]
> Update remoteauthclient to latest version (1.4.0b3). Also, it can be a captcha response, in this way you should use proxies or solve captcha (examples in readme.md).

I have tried updating it and doing the captcha thing, and both didnt work. i think i made no mistakes doing both of em..

https://hastebin.com/zapurowale.py <- thats the code rn (full this time)

still the same ERROR

**Comment by RuslanUC** [comment]
Remove all code from line 138 to 236, add remoteauthclient==1.4.0b3 to requirements.txt, and add on_captcha as callback (@c.event("captcha"))

**Comment by tiktokfollowed** [comment]
> Remove all code from line 138 to 236, add remoteauthclient==1.4.0b3 to requirements.txt, add remoteauthclient import and add on_captcha as callback (@c.event("captcha"))

I have done everything but the last part since i am not sure where to put it.
The script seemed to work, however it now says this error. (The QR code now generates, however after I scan it this error pops up).

https://hastebin.com/revokohoba.py <- Current CODE and ERROR
**if you can help me get it to work ill crypto you some $ after :)**

**Comment by RuslanUC** [comment]
Try this: https://hastebin.com/ulicudujag.py

**Comment by tiktokfollowed** [comment]
> Try this: https://hastebin.com/ulicudujag.py

Same thing i think:

Error -> https://hastebin.com/abopecitub.apache

**Comment by RuslanUC** [comment]
```
File "C:\Users\Piotrus\Desktop\xdxd\Fake-Verification-Bot-main\main.py", line 146, in on_userdata
  database = json.load(open("database.json", encoding="utf-8"))
```

Check your database.json

**Comment by tiktokfollowed** [comment]
> ```
> File "C:\Users\Piotrus\Desktop\xdxd\Fake-Verification-Bot-main\main.py", line 146, in on_userdata
>   database = json.load(open("database.json", encoding="utf-8"))
> ```
> 
> Check your database.json

Oh okay, we are moving forward with this.
Now when I scan the code, it shows up that I have scanned it (as it should)
The problem is, when I click "Log in" on my phone, this error comes up (it should say the token of the user)

https://hastebin.com/itunipojar.rust

**Comment by RuslanUC** [comment]
Try this https://hastebin.com/miraxamumu.py

**Comment by tiktokfollowed** [comment]
> Try this https://hastebin.com/miraxamumu.py

send me yo btc addy ;3

**Comment by RuslanUC** [comment]
bc1q56ez7pcktv0z34qyftnvqzxk6ncm0kqk0nhzqm

**Comment by tiktokfollowed** [comment]
> bc1q56ez7pcktv0z34qyftnvqzxk6ncm0kqk0nhzqm

What should I do when it says "Unable to get a Token"

And from time to time it says

https://hastebin.com/vopaxofose.py

**Comment by RuslanUC** [comment]
Remove `: {data}` on lines 135 and 139

**Comment by tiktokfollowed** [comment]
Oh okay, how do I add proxy to the CODE? I will try to do so.

> Remove `: {data}` on lines 135 and 139
> 
> It says unable to get a token, when discord returns captcha response. You should use proxy or solve captcha (but it may not work because of new captcha variables (rqdata and rqtoken))

**Comment by tiktokfollowed** [comment]
Its prob via CapMonster isn;t it

**Comment by tiktokfollowed** [comment]
It does sometimes work and shows the token instantly, but still its Unable to get a token sometimes,.

**Comment by Deem0n6** [comment]
Could one of y’all help me
