### ISSUE TITLE
Какие прокси юзать для бота Fake Verify Bot?

### ISSUE THREAD

**Issue by 98wa90w09w** [RuslanUC/RemoteAuthClient#9]
Шапка, что с socks5, что с https, что с http ошибки вылетают.

**Comment by RuslanUC** [comment]
Используйте https, указывая только адрес и порт (без https://)

**Comment by 98wa90w09w** [comment]
При этом я все равно получаю ошибку, используя https прокси.
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<RemoteAuthClient.run() done, defined at C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\remoteauthclient\remoteauthclient.py:193> exception=ClientHttpProxyError(RequestInfo(url=URL('https://discord.com/api/v9/users/@me/remote-auth/login'), method='CONNECT', headers=<CIMultiDictProxy('Host': 'discord.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>, real_url=URL('http://185.250.243.78:33128')), (), status=403, message='Forbidden', headers=<CIMultiDictProxy('Server': 'squid', 'Mime-Version': '1.0', 'Date': 'Thu, 29 Sep 2022 14:24:40 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Content-Length': '3653', 'X-Squid-Error': 'ERR_ACCESS_DENIED 0', 'Vary': 'Accept-Language', 'Content-Language': 'en', 'X-Cache': 'MISS from dc', 'X-Cache-Lookup': 'NONE from dc:33128', 'Connection': 'keep-alive')>)>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\remoteauthclient\remoteauthclient.py", line 196, in run
    await self._task
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\remoteauthclient\remoteauthclient.py", line 178, in _run
    encryptedToken = await self._getToken(p["ticket"])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\remoteauthclient\remoteauthclient.py", line 129, in _getToken
    resp = await sess.post("https://discord.com/api/v9/users/@me/remote-auth/login", json=data, **_proxy)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1288, in _create_proxy_connection
    raise ClientHttpProxyError(
aiohttp.client_exceptions.ClientHttpProxyError: 403, message='Forbidden', url=URL('http://185.250.243.78:33128')

**Comment by RuslanUC** [comment]
Похоже на прокси с авторизацией, используйте аргумент proxy_auth (как указано в readme), если это так.

**Comment by 98wa90w09w** [comment]
Нет, прокси без авторизации. Возможно, это из за тестирования на паблик прокси, так как приват прокси у меня только socks5.

**Comment by 98wa90w09w** [comment]
На прокси с поддержкой HTTPS и HTTP сразу же получилось добиться хоть какого то результата, теперь написано Unable to get a token.
Впрочем, это все равно не тот результат, который я хочу получить.

**Comment by RuslanUC** [comment]
Unable to get a token из-за того, что дискорд возвращает капчу вместо токена

**Comment by 98wa90w09w** [comment]
И чем  ещё можно обойти данную капчу, если вы рекомендовали прокси?

**Comment by RuslanUC** [comment]
Попробуйте capmonster, но, возможно он не сможет решить эту капчу (дискорд использует какой-то новый тип капчи с rqtoken и rqdata).

**Comment by 98wa90w09w** [comment]
Ох, сколько же заморочек с лишь одним ботом. Прокси не помогают, надо использовать всякие анти капчи, которые могут даже не помочь. Пожалуй, лучше не использовать данного бота вообще, хоть и идея классная. Упомяните пожалуйста, когда будет нормальный фикс бота.

**Comment by RuslanUC** [comment]
Ок, но нормальный фикс будет, скорее всего, когда будет работать анти-капча, ибо иначе токен не получить

**Comment by 98wa90w09w** [comment]
Есть предположение, что бота можно починить, «поигравшись» с chromedriver (нужен естественно google chrome), а также поиграться  придётся с выполнением команд в консоли браузера также через chromedriver, так как при получении токена через консоль браузера капчи нет.

**Comment by RuslanUC** [comment]
Через chromedriver можно, видел даже репозиторий, где сделали решение hcaptcha через нейросеть и chromedriver, однако remoteauthclient изначально задумывался как авторизация по qr коду без браузера.

**Comment by RuslanUC** [comment]
И, кстати, через браузер капча есть, но попадается гораздо реже. Как вариант - можно прописать [тут](https://github.com/RuslanUC/RemoteAuthClient/blob/main/remoteauthclient/remoteauthclient.py#L124) реалистичные заголовки для запроса. Но, скорее всего, если использовать модуль для ботов, которых будут часто использовать - никакие заголовки не помогут.

**Comment by 98wa90w09w** [comment]
Есть ещё вариант - как то сделать так, чтобы бот перехватывал запрос science при входе в аккаунт из вкладки Network в панели разработчика, так как там тоже пишется токен.

**Comment by RuslanUC** [comment]
К сожалению, запрос science выполняется только после входа, т.е. после получения токена.
